main: net.urbanmc.treasurehunter.TreasureHunter
name: TreasureHunter
version: 1.0
api-version: 1.14
description: Spawns chests around the world at intervals containing various loot
authors: [Elian, Silverwolfg11]
softdepend: [Multiverse-Core, Essentials, EssentialsSpawn, Towny]

commands:
  treasurehunter:
    description: TreasureHunter command
    aliases: [th]

permissions:
  treasurehunter.*:
    default: op
    children:
      treasurehunter.default: true
      treasurehunter.tp: true
      treasurehunter.spawn: true
      treasurehunter.reload: true
  treasurehunter.default:
    default: true
    children:
      treasurehunter.command: true
      treasurehunter.start: true
      treasurehunter.cancel: true
      treasurehunter.chests: true
      treasurehunter.status: true
  treasurehunter.command:
    default: false
  treasurehunter.start:
    default: false
  treasurehunter.cancel:
      default: false
  treasurehunter.chests:
      default: false
  treasurehunter.tp:
      default: false
  treasurehunter.spawn:
      default: false
  treasurehunter.reload:
      default: false
  treasurehunter.status:
      default: false